### ISSUE TITLE
Add support for diagrams-rasterific backend

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [bollu/cellularAutomata#1]
As cairo is notoriously difficult to install on osx and rasterific is a native haskell library that supports animated gifs.

**Comment by d12frosted** [comment]
Am I missing something or `brew install cairo` does the trick?

**Comment by bollu** [comment]
I think he meant the haskell bindings for `cairo`, and not cairo itself.

**Comment by d12frosted** [comment]
Ah, I see. What about `stack install cairo`? :)

**Comment by bollu** [comment]
heh, I think there are some compilation issues that one can have with OSX - I haven't faced them, but I have with other libraries (eg. `ghc-mod`)

Plus it's a good idea to support as many backends as possible anyway - variety is the spice of life :)

**Comment by bollu** [comment]
Done! I've made the code backend-agnostic
